name: XCS224N
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy=1.24.3
  - scipy=1.10.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - tqdm=4.65.0
  - docopt=0.6.2
  - notebook=7.0.6
  - pip=23.3.1
  - tensorboard
  - pip:
    - sentencepiece
    - sacrebleu
    - nltk
    - timeout_decorator
    - lxml==4.9.4; sys_platform != "linux" and sys_platform != "win32"
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==2.1.2; sys_platform != "linux" and sys_platform != "win32"
    - torch==2.1.2+cpu; sys_platform == "linux" or sys_platform == "win32"